version: '3.8'
services:
  postgres_db:
    container_name: postgres_SCRIBEAI
    image: postgres:16-alpine
    hostname: localhost
    environment: 
      POSTGRES_DB: SCRIBEAI_DB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: myperfectpassword
    ports: 
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data: 


